// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueueInterface is an autogenerated mock type for the QueueInterface type
type QueueInterface struct {
	mock.Mock
}

// EnqueueOrder provides a mock function with given fields: userID, orderNum
func (_m *QueueInterface) EnqueueOrder(userID int, orderNum string) {
	_m.Called(userID, orderNum)
}

// NewQueueInterface creates a new instance of QueueInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueInterface {
	mock := &QueueInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
