// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/scoring-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	service "github.com/scoring-service/internal/service"
)

// ServiceInterface is an autogenerated mock type for the ServiceInterface type
type ServiceInterface struct {
	mock.Mock
}

type ServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceInterface) EXPECT() *ServiceInterface_Expecter {
	return &ServiceInterface_Expecter{mock: &_m.Mock}
}

// AuthorizeUser provides a mock function with given fields: ctx, user
func (_m *ServiceInterface) AuthorizeUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceInterface_AuthorizeUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeUser'
type ServiceInterface_AuthorizeUser_Call struct {
	*mock.Call
}

// AuthorizeUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *ServiceInterface_Expecter) AuthorizeUser(ctx interface{}, user interface{}) *ServiceInterface_AuthorizeUser_Call {
	return &ServiceInterface_AuthorizeUser_Call{Call: _e.mock.On("AuthorizeUser", ctx, user)}
}

func (_c *ServiceInterface_AuthorizeUser_Call) Run(run func(ctx context.Context, user *models.User)) *ServiceInterface_AuthorizeUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *ServiceInterface_AuthorizeUser_Call) Return(_a0 error) *ServiceInterface_AuthorizeUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceInterface_AuthorizeUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *ServiceInterface_AuthorizeUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, userId, orderNum
func (_m *ServiceInterface) CreateOrder(ctx context.Context, userId int, orderNum string) service.CreateStatus {
	ret := _m.Called(ctx, userId, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 service.CreateStatus
	if rf, ok := ret.Get(0).(func(context.Context, int, string) service.CreateStatus); ok {
		r0 = rf(ctx, userId, orderNum)
	} else {
		r0 = ret.Get(0).(service.CreateStatus)
	}

	return r0
}

// ServiceInterface_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type ServiceInterface_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - orderNum string
func (_e *ServiceInterface_Expecter) CreateOrder(ctx interface{}, userId interface{}, orderNum interface{}) *ServiceInterface_CreateOrder_Call {
	return &ServiceInterface_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userId, orderNum)}
}

func (_c *ServiceInterface_CreateOrder_Call) Run(run func(ctx context.Context, userId int, orderNum string)) *ServiceInterface_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *ServiceInterface_CreateOrder_Call) Return(_a0 service.CreateStatus) *ServiceInterface_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceInterface_CreateOrder_Call) RunAndReturn(run func(context.Context, int, string) service.CreateStatus) *ServiceInterface_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithdraw provides a mock function with given fields: ctx, userId, withdraw
func (_m *ServiceInterface) CreateWithdraw(ctx context.Context, userId int, withdraw models.Withdraw) service.CreateStatus {
	ret := _m.Called(ctx, userId, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithdraw")
	}

	var r0 service.CreateStatus
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Withdraw) service.CreateStatus); ok {
		r0 = rf(ctx, userId, withdraw)
	} else {
		r0 = ret.Get(0).(service.CreateStatus)
	}

	return r0
}

// ServiceInterface_CreateWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithdraw'
type ServiceInterface_CreateWithdraw_Call struct {
	*mock.Call
}

// CreateWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - withdraw models.Withdraw
func (_e *ServiceInterface_Expecter) CreateWithdraw(ctx interface{}, userId interface{}, withdraw interface{}) *ServiceInterface_CreateWithdraw_Call {
	return &ServiceInterface_CreateWithdraw_Call{Call: _e.mock.On("CreateWithdraw", ctx, userId, withdraw)}
}

func (_c *ServiceInterface_CreateWithdraw_Call) Run(run func(ctx context.Context, userId int, withdraw models.Withdraw)) *ServiceInterface_CreateWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.Withdraw))
	})
	return _c
}

func (_c *ServiceInterface_CreateWithdraw_Call) Return(_a0 service.CreateStatus) *ServiceInterface_CreateWithdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceInterface_CreateWithdraw_Call) RunAndReturn(run func(context.Context, int, models.Withdraw) service.CreateStatus) *ServiceInterface_CreateWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function with given fields: ctx, id
func (_m *ServiceInterface) GetUserBalance(ctx context.Context, id int) (models.Balance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 models.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Balance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Balance); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Balance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInterface_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type ServiceInterface_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ServiceInterface_Expecter) GetUserBalance(ctx interface{}, id interface{}) *ServiceInterface_GetUserBalance_Call {
	return &ServiceInterface_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, id)}
}

func (_c *ServiceInterface_GetUserBalance_Call) Run(run func(ctx context.Context, id int)) *ServiceInterface_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ServiceInterface_GetUserBalance_Call) Return(_a0 models.Balance, _a1 error) *ServiceInterface_GetUserBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceInterface_GetUserBalance_Call) RunAndReturn(run func(context.Context, int) (models.Balance, error)) *ServiceInterface_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function with given fields: ctx, id
func (_m *ServiceInterface) GetUserOrders(ctx context.Context, id int) ([]models.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInterface_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type ServiceInterface_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ServiceInterface_Expecter) GetUserOrders(ctx interface{}, id interface{}) *ServiceInterface_GetUserOrders_Call {
	return &ServiceInterface_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, id)}
}

func (_c *ServiceInterface_GetUserOrders_Call) Run(run func(ctx context.Context, id int)) *ServiceInterface_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ServiceInterface_GetUserOrders_Call) Return(_a0 []models.Order, _a1 error) *ServiceInterface_GetUserOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceInterface_GetUserOrders_Call) RunAndReturn(run func(context.Context, int) ([]models.Order, error)) *ServiceInterface_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithdrawals provides a mock function with given fields: ctx, id
func (_m *ServiceInterface) GetUserWithdrawals(ctx context.Context, id int) ([]models.Withdrawal, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithdrawals")
	}

	var r0 []models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Withdrawal, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Withdrawal); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInterface_GetUserWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithdrawals'
type ServiceInterface_GetUserWithdrawals_Call struct {
	*mock.Call
}

// GetUserWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ServiceInterface_Expecter) GetUserWithdrawals(ctx interface{}, id interface{}) *ServiceInterface_GetUserWithdrawals_Call {
	return &ServiceInterface_GetUserWithdrawals_Call{Call: _e.mock.On("GetUserWithdrawals", ctx, id)}
}

func (_c *ServiceInterface_GetUserWithdrawals_Call) Run(run func(ctx context.Context, id int)) *ServiceInterface_GetUserWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ServiceInterface_GetUserWithdrawals_Call) Return(_a0 []models.Withdrawal, _a1 error) *ServiceInterface_GetUserWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceInterface_GetUserWithdrawals_Call) RunAndReturn(run func(context.Context, int) ([]models.Withdrawal, error)) *ServiceInterface_GetUserWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// ReagisterUser provides a mock function with given fields: ctx, user
func (_m *ServiceInterface) ReagisterUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ReagisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceInterface_ReagisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReagisterUser'
type ServiceInterface_ReagisterUser_Call struct {
	*mock.Call
}

// ReagisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *ServiceInterface_Expecter) ReagisterUser(ctx interface{}, user interface{}) *ServiceInterface_ReagisterUser_Call {
	return &ServiceInterface_ReagisterUser_Call{Call: _e.mock.On("ReagisterUser", ctx, user)}
}

func (_c *ServiceInterface_ReagisterUser_Call) Run(run func(ctx context.Context, user *models.User)) *ServiceInterface_ReagisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *ServiceInterface_ReagisterUser_Call) Return(_a0 error) *ServiceInterface_ReagisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceInterface_ReagisterUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *ServiceInterface_ReagisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// UserExist provides a mock function with given fields: ctx, login
func (_m *ServiceInterface) UserExist(ctx context.Context, login string) (bool, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for UserExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInterface_UserExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExist'
type ServiceInterface_UserExist_Call struct {
	*mock.Call
}

// UserExist is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *ServiceInterface_Expecter) UserExist(ctx interface{}, login interface{}) *ServiceInterface_UserExist_Call {
	return &ServiceInterface_UserExist_Call{Call: _e.mock.On("UserExist", ctx, login)}
}

func (_c *ServiceInterface_UserExist_Call) Run(run func(ctx context.Context, login string)) *ServiceInterface_UserExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ServiceInterface_UserExist_Call) Return(_a0 bool, _a1 error) *ServiceInterface_UserExist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceInterface_UserExist_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *ServiceInterface_UserExist_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceInterface creates a new instance of ServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterface {
	mock := &ServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
