// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/scoring-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageInterface is an autogenerated mock type for the StorageInterface type
type StorageInterface struct {
	mock.Mock
}

type StorageInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageInterface) EXPECT() *StorageInterface_Expecter {
	return &StorageInterface_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *StorageInterface) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type StorageInterface_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *StorageInterface_Expecter) CreateUser(ctx interface{}, user interface{}) *StorageInterface_CreateUser_Call {
	return &StorageInterface_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *StorageInterface_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *StorageInterface_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *StorageInterface_CreateUser_Call) Return(_a0 error) *StorageInterface_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *StorageInterface_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingOrders provides a mock function with given fields: ctx
func (_m *StorageInterface) GetPendingOrders(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOrders")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingOrders'
type StorageInterface_GetPendingOrders_Call struct {
	*mock.Call
}

// GetPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageInterface_Expecter) GetPendingOrders(ctx interface{}) *StorageInterface_GetPendingOrders_Call {
	return &StorageInterface_GetPendingOrders_Call{Call: _e.mock.On("GetPendingOrders", ctx)}
}

func (_c *StorageInterface_GetPendingOrders_Call) Run(run func(ctx context.Context)) *StorageInterface_GetPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageInterface_GetPendingOrders_Call) Return(_a0 []string, _a1 error) *StorageInterface_GetPendingOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetPendingOrders_Call) RunAndReturn(run func(context.Context) ([]string, error)) *StorageInterface_GetPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function with given fields: ctx, userID
func (_m *StorageInterface) GetUserBalance(ctx context.Context, userID int) (models.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 models.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.Balance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type StorageInterface_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *StorageInterface_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *StorageInterface_GetUserBalance_Call {
	return &StorageInterface_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *StorageInterface_GetUserBalance_Call) Run(run func(ctx context.Context, userID int)) *StorageInterface_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *StorageInterface_GetUserBalance_Call) Return(_a0 models.Balance, _a1 error) *StorageInterface_GetUserBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetUserBalance_Call) RunAndReturn(run func(context.Context, int) (models.Balance, error)) *StorageInterface_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function with given fields: ctx, login
func (_m *StorageInterface) GetUserByLogin(ctx context.Context, login string) (*models.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type StorageInterface_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *StorageInterface_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *StorageInterface_GetUserByLogin_Call {
	return &StorageInterface_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *StorageInterface_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *StorageInterface_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageInterface_GetUserByLogin_Call) Return(_a0 *models.User, _a1 error) *StorageInterface_GetUserByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetUserByLogin_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *StorageInterface_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function with given fields: ctx, userID
func (_m *StorageInterface) GetUserOrders(ctx context.Context, userID int) ([]models.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type StorageInterface_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *StorageInterface_Expecter) GetUserOrders(ctx interface{}, userID interface{}) *StorageInterface_GetUserOrders_Call {
	return &StorageInterface_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, userID)}
}

func (_c *StorageInterface_GetUserOrders_Call) Run(run func(ctx context.Context, userID int)) *StorageInterface_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *StorageInterface_GetUserOrders_Call) Return(_a0 []models.Order, _a1 error) *StorageInterface_GetUserOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetUserOrders_Call) RunAndReturn(run func(context.Context, int) ([]models.Order, error)) *StorageInterface_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithdrawals provides a mock function with given fields: ctx, userID
func (_m *StorageInterface) GetUserWithdrawals(ctx context.Context, userID int) ([]models.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithdrawals")
	}

	var r0 []models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetUserWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithdrawals'
type StorageInterface_GetUserWithdrawals_Call struct {
	*mock.Call
}

// GetUserWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *StorageInterface_Expecter) GetUserWithdrawals(ctx interface{}, userID interface{}) *StorageInterface_GetUserWithdrawals_Call {
	return &StorageInterface_GetUserWithdrawals_Call{Call: _e.mock.On("GetUserWithdrawals", ctx, userID)}
}

func (_c *StorageInterface_GetUserWithdrawals_Call) Run(run func(ctx context.Context, userID int)) *StorageInterface_GetUserWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *StorageInterface_GetUserWithdrawals_Call) Return(_a0 []models.Withdrawal, _a1 error) *StorageInterface_GetUserWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetUserWithdrawals_Call) RunAndReturn(run func(context.Context, int) ([]models.Withdrawal, error)) *StorageInterface_GetUserWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// IsOrderExists provides a mock function with given fields: ctx, orderNum
func (_m *StorageInterface) IsOrderExists(ctx context.Context, orderNum string) (int, error) {
	ret := _m.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for IsOrderExists")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, orderNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, orderNum)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_IsOrderExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOrderExists'
type StorageInterface_IsOrderExists_Call struct {
	*mock.Call
}

// IsOrderExists is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
func (_e *StorageInterface_Expecter) IsOrderExists(ctx interface{}, orderNum interface{}) *StorageInterface_IsOrderExists_Call {
	return &StorageInterface_IsOrderExists_Call{Call: _e.mock.On("IsOrderExists", ctx, orderNum)}
}

func (_c *StorageInterface_IsOrderExists_Call) Run(run func(ctx context.Context, orderNum string)) *StorageInterface_IsOrderExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageInterface_IsOrderExists_Call) Return(_a0 int, _a1 error) *StorageInterface_IsOrderExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_IsOrderExists_Call) RunAndReturn(run func(context.Context, string) (int, error)) *StorageInterface_IsOrderExists_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, user, order
func (_m *StorageInterface) SaveOrder(ctx context.Context, user int, order *models.Order) error {
	ret := _m.Called(ctx, user, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Order) error); ok {
		r0 = rf(ctx, user, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type StorageInterface_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - user int
//   - order *models.Order
func (_e *StorageInterface_Expecter) SaveOrder(ctx interface{}, user interface{}, order interface{}) *StorageInterface_SaveOrder_Call {
	return &StorageInterface_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, user, order)}
}

func (_c *StorageInterface_SaveOrder_Call) Run(run func(ctx context.Context, user int, order *models.Order)) *StorageInterface_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Order))
	})
	return _c
}

func (_c *StorageInterface_SaveOrder_Call) Return(_a0 error) *StorageInterface_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_SaveOrder_Call) RunAndReturn(run func(context.Context, int, *models.Order) error) *StorageInterface_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, accrual
func (_m *StorageInterface) UpdateOrder(ctx context.Context, accrual *models.AccrualResponse) error {
	ret := _m.Called(ctx, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AccrualResponse) error); ok {
		r0 = rf(ctx, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type StorageInterface_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - accrual *models.AccrualResponse
func (_e *StorageInterface_Expecter) UpdateOrder(ctx interface{}, accrual interface{}) *StorageInterface_UpdateOrder_Call {
	return &StorageInterface_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, accrual)}
}

func (_c *StorageInterface_UpdateOrder_Call) Run(run func(ctx context.Context, accrual *models.AccrualResponse)) *StorageInterface_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AccrualResponse))
	})
	return _c
}

func (_c *StorageInterface_UpdateOrder_Call) Return(_a0 error) *StorageInterface_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_UpdateOrder_Call) RunAndReturn(run func(context.Context, *models.AccrualResponse) error) *StorageInterface_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, order, sum
func (_m *StorageInterface) Withdraw(ctx context.Context, userID int, order string, sum float64) error {
	ret := _m.Called(ctx, userID, order, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, float64) error); ok {
		r0 = rf(ctx, userID, order, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type StorageInterface_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - order string
//   - sum float64
func (_e *StorageInterface_Expecter) Withdraw(ctx interface{}, userID interface{}, order interface{}, sum interface{}) *StorageInterface_Withdraw_Call {
	return &StorageInterface_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, order, sum)}
}

func (_c *StorageInterface_Withdraw_Call) Run(run func(ctx context.Context, userID int, order string, sum float64)) *StorageInterface_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *StorageInterface_Withdraw_Call) Return(_a0 error) *StorageInterface_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_Withdraw_Call) RunAndReturn(run func(context.Context, int, string, float64) error) *StorageInterface_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageInterface creates a new instance of StorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageInterface {
	mock := &StorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
